/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  appDirectory: "app",
  browserBuildDirectory: "public/build",
  publicPath: "/build/",
  serverBuildDirectory: "build",
  devServerPort: 8002,
  // TODO: when mui has esm support, remove this (default is esm)
  // check it https://github.com/mui/material-ui/issues/30671
  serverModuleFormat: "cjs",
  browserNodeBuiltinsPolyfill: {
    modules: {
      tty: true,
      fs: true,
      util: true,
      path: true,
      os: true,
      crypto: true,
      stream: true,
      buffer: true,
      assert: true,
      events: true,
      http: true,
      https: true,
      url: true,
      querystring: true,
      punycode: true,
      zlib: true,
      string_decoder: true,
      process: true,
      vm: true,
      timers: true,
      console: true,
      constants: true,
      dns: true,
      domain: true,
      net: true,
      readline: true,
      repl: true,
      tls: true,
      dgram: true,
      child_process: true,
      cluster: true,
      module: true
    },
  },
};
